// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkypjhpwzxztbvdtjxla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJreXBqaHB3enh6dGJ2ZHRqeGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzk2NTYsImV4cCI6MjA2NDgxNTY1Nn0.MEeopxHr8Ut_EkKTpKh1_EcYXtfxxPPCNI0841StlY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);